name: Mirror to GitLab

on:
  push:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth : 0 #코드의 모든 히스토리를 가지고 온다. 0이 아닌 양수의 경우 해당 깊이만큼만 가지고 온디

    - name: set remote repository
      env :
        gitlab_url: ${{ secrets.GITLAB_URL }}
        gitlab_username: ${{ secrets.GITLAB_USERNAME }}
        gitlab_token: ${{ secrets.GITLAB_TOKEN }}
      run: | # 토큰을 조합해서 url을 만든다.
        git remote add gitlab https://${gitlab_username}:${gitlab_token}@${gitlab_url#https://};

    - name: Force push everthing
      run: | # 모든 브랜치와 태그에 대하여 push합니다. gitlab에서 보호설정이 걸려있으면 Fail할 수 있습니다.
        git push -f --all gitlab;
        git push -f --tags gitlab;
      
